spring:
  application:
    name: RATING-SERVICE
  data:
    mongodb:
      uri: mongodb://root:example@localhost:27017/hotel-microservice?authSource=admin

server:
  port: 8083
  servlet:
    context-path: /api/v1

eureka:
  instance:
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/