spring:
  application:
    name: RATING-SERVICE
  data:
    mongodb:
      uri: mongodb://root:example@localhost:27017/hotel-microservice?authSource=admin
  config:
    import: "configserver:http://localhost:8084"


server:
  port: 8083
