spring:
  application:
    name: RatingService
  data:
    mongodb:
      uri: mongodb://root:example@localhost:27017/hotel-microservice?authSource=admin

server:
  port: 8083
  servlet:
    context-path: /api/v1